spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5433/chat_db
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop